version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=itida
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local

networks:
  mysql-network:
    driver: bridge